### PR TITLE
Simplify `mergePromise` function

### PR DESCRIPTION
**Pull request by fisker**
Simplify `mergePromise` function, and clean up tests

### CODE REVIEW

**Comment by ehmicky** [comment]
Hi @fisker,

Would it be possible to split this PR into two separate PRs: one for the tests cleanup, and one for the `mergePromise` function refactoring? Thanks a lot.

**Comment by fisker** [comment]
@ehmicky #405

**Comment by fisker** [comment]
strange... failed

**Comment by ehmicky** [comment]
This looks good to me.
@sindresorhus what do you think?

**Comment by sindresorhus** [comment]
Looks good

**Pull request merged**
