### PR TITLE
Fix functions coding style

### PR DESCRIPTION
**Pull request by ehmicky**
This makes all functions use the `const funcName = (...) => {...}` coding style.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by ehmicky** [comment]
Fixed.

**Comment by kirillgroshkov** [comment]
Any reference to why this style is preferred? (just curious for myself)

**Comment by ehmicky** [comment]
I don't think it matters too much, what matters for me most is consistency. Actually this is @sindresorhus preferred style, I am using a [different style](https://github.com/ehmicky/log-process-errors/blob/master/src/level.js#L7) for my other projects.

Also I don't like to rely on hoisting.

**Comment by sindresorhus** [comment]
Mostly for consistency, more sane hoisting rules, and ability to have inline arrow functions statements.

**Pull request merged**
