### PR TITLE
Rename `.cmd` to `.command`

### LINKED ISSUE #190: Rename `. cmd` to `.command`
In the result object and error property. Since we're doing a major release, it would be nice to make the output more readable.

### PR DESCRIPTION
**Pull request by satyarohith**
closes #190

### CODE REVIEW

**Comment by satyarohith** [comment]
Thanks for your kindness! Updated!

**Comment by ehmicky** [comment]
Looks good to me, thanks for this PR! :tada: 	

Waiting for review from @sindresorhus before merging.

**Comment by sindresorhus** [comment]
Can you also update https://github.com/sindresorhus/execa/blob/master/index.d.ts and https://github.com/sindresorhus/execa/blob/master/index.test-d.ts?

**Comment by satyarohith** [comment]
@sindresorhus Updated! :tada:

**Comment by sindresorhus** [comment]
Looks great :)

**Pull request merged**
