### PR TITLE
Add retry example to `Tips` readme section

### LINKED ISSUE #362: feat: handle EAGAIN
Sometimes, process creation can fail due to various external reasons. e.g. when `fork` is temporarily unavailable, error code of `EAGAIN` will be issued. I think would be great if execa has an extra option for setting number of trials when hitting `EAGAIN` error.

Thanks

### PR DESCRIPTION
**Pull request by justsml**
Fixes #362

This addresses a need I had.

### CODE REVIEW

**Comment by ehmicky** [comment]
Thanks @justsml for this PR!

I like the idea. However I am not so sure about referring to that specific library `promise-retry`. It seems like it has not received any commits for quite some time, and PR/issues are not processed anymore.

On the other hand, a library like [`p-retry`](https://github.com/sindresorhus/p-retry) is maintained and has more features. What do you think?

**Comment by justsml** [comment]
Strong agree @ehmicky ... I'll get it updated. 🤘

**Comment by ehmicky** [comment]
This looks good now, thanks!

**Comment by sindresorhus** [comment]
`Retry on Error` => `Retry on error`

**Comment by justsml** [comment]
Fixed title: 'Error' => 'error'

**Pull request merged**
